### PR TITLE
Error use of multitenancy with T0 gateways

### PR DESCRIPTION
**Pull request by ksamoray**
T0 gateways do not have multitenancy support

### CODE REVIEW

**Comment by annakhm** [comment]
LGTM but I would suggest to move the message string out to avoid duplication, and change `multitenancy` to `context` to be more precise

**Comment by ksamoray** [comment]
> LGTM but I would suggest to move the message string out to avoid duplication, and change `multitenancy` to `context` to be more precise

Makes sense, I'll revise it.

**Review by annakhm — APPROVED** [review]

**Pull request merged**
