### PR TITLE
Skip marked_for_delete data sources in search by name/type

### PR DESCRIPTION
**Pull request by asarfaty**

### CODE REVIEW

**Review by annakhm — COMMENTED** [review]
Should we add the same check to listPolicyResourcesByID?

**Review by annakhm — APPROVED** [review]
Pls ignore the website linter error - its already fixed

**Comment by asarfaty** [comment]
> Should we add the same check to listPolicyResourcesByID?

I'm not sure. I think if you ask for a specific ID you probably know what you want so its unlikely to be deleted. But we can if you think so.

**Comment by annakhm** [comment]
We should be consistent with LM behavior. Do you know if GET for an object would return it in case its marked for deletion?

**Comment by asarfaty** [comment]
No. Regular GET (or LIST) does not return those.

**Review by annakhm — APPROVED** [review]
Thx!

**Pull request merged**
