### PR TITLE
Expose dhcp v6 static binding resource

### PR DESCRIPTION
**Pull request by annakhm**

### CODE REVIEW

**Comment by asarfaty** [comment]
Seems like the documentations is missing?

**Comment by annakhm** [comment]
Thanks Adit, added the doc

**Comment by asarfaty** [comment]
Still seems like website/docs/r/policy_dhcp_v4_static_binding_config.html.markdown  was deleted in this pull request

**Comment by annakhm** [comment]
Thanks :) added back

**Review by asarfaty — APPROVED** [review]

**Pull request merged**
