### PR TITLE
Update documentation for nsxt_policy_user_management_role_binding

### PR DESCRIPTION
**Pull request by salv-orlando**
This change highlights dependencies of this resource in documentation.

### CODE REVIEW

**Comment by ksamoray** [comment]
As NSX associates  `nsxt_policy_user_management_role_binding` with `nsxt_node_user` by matching the name attribute, you could associate these by setting the name attribute to the `nsxt_node_user` username, e.g:
```
resource "nsxt_policy_user_management_role_binding" "user_management_role_binding" {
  display_name         = "johndoe123"
  name                 = nsxt_node_user.node_user.username
  type                 = "local_user"
  roles_for_path {
    path  = "/"
    roles = ["auditor"]
  }
  overwrite_local_user = true
}
``` 
Instead of having an explicit dependency.

**Comment by annakhm** [comment]
> As NSX associates `nsxt_policy_user_management_role_binding` with `nsxt_node_user` by matching the name attribute, you could associate these by setting the name attribute to the `nsxt_node_user` username, e.g:
> 
> ```
> resource "nsxt_policy_user_management_role_binding" "user_management_role_binding" {
>   display_name         = "johndoe123"
>   name                 = nsxt_node_user.node_user.username
>   type                 = "local_user"
>   roles_for_path {
>     path  = "/"
>     roles = ["auditor"]
>   }
>   overwrite_local_user = true
> }
> ```
> 
> Instead of having an explicit dependency.

Unfortunately this would not work, since `nsxt_node_user.node_user.username` is known at plan time, so terraform doesn't feel the need to wait for the resource.
What would work is forcing the user to specify explicit dependency, such as defining required attribute `node_user_id`. Lets consider this?

**Review by ksamoray — APPROVED** [review]
Understood @annakhm explanation, LGTM

**Comment by annakhm** [comment]
I'm fine with this solution as well

**Pull request merged**
