### PR TITLE
[MdProxy] Read secret attribute

### PR DESCRIPTION
**Pull request by salv-orlando**
The NSX API returns the metadata secret and therefore it should be parsed by the read function.

This change also amends the import test to remove the ignore statement for the secret attribute.

### CODE REVIEW

**Comment by salv-orlando** [comment]
Failure for lm-3.2.3 job occurred in `TestAccResourceNsxtEdgeCluster_basic` which is not related to this PR.

**Review by ksamoray — APPROVED** [review]
LGTM. Change can be rebased to satisfy the website linter.

**Review by annakhm — APPROVED** [review]
I hope its ok to follow the API with this :)

**Pull request merged**
