### PR TITLE
Remove redundant data source

### PR DESCRIPTION
**Pull request by annakhm**

### CODE REVIEW

**Review by tenthirtyam — COMMENTED** [review]
I'd recommend enhancing this pull request to put all resources and data sources in alphabetical order. 

Duplicates will easier to spot and the code is more logically ordered and readable.

**Comment by annakhm** [comment]
Good point @tenthirtyam, however I'd rather postpone this one until after the Big Merge, to minimize merge errors

**Comment by tenthirtyam** [comment]
Totally understand!

**Review by ksamoray — APPROVED** [review]

**Review by salv-orlando — APPROVED** [review]
LGTM

**Pull request merged**
