### PR TITLE
Consistent naming in TN data source

### PR DESCRIPTION
**Pull request by annakhm**

### CODE REVIEW

**Comment by ksamoray** [comment]
This DS retrieves all kinds of transport nodes - so if we rename it, we should at least filter out non-edge TNs.

**Comment by ksamoray** [comment]
If we choose to rename, can we also rename the realization DS `nsxt_transport_node_realization`?

**Comment by annakhm** [comment]
> This DS retrieves all kinds of transport nodes - so if we rename it, we should at least filter out non-edge TNs.

This PR changes the TN to be generic, by removing `edge` from naming

**Comment by ksamoray** [comment]
> > This DS retrieves all kinds of transport nodes - so if we rename it, we should at least filter out non-edge TNs.
> 
> This PR changes the TN to be generic, by removing `edge` from naming

Got it... Seems like "someone" made a mess here :)

**Review by ksamoray — APPROVED** [review]
Thanks!

**Pull request merged**
