### PR TITLE
Support replication mode in Segment resources

### PR DESCRIPTION
**Pull request by annakhm**
This attribute was added in NSX 3.0.0
In addition, remove cidr requirement for segment subnet, as
its no longer required on the platform.

Signed-off-by: Anna Khmelnitsky <akhmelnitsky@vmware.com>

### CODE REVIEW

**Review by 2ez4szliu — APPROVED** [review]

**Comment by coteforbes** [comment]
Can we update the documentation in the registry to reflect this change?  Thanks!

**Comment by annakhm** [comment]
Yes @coteforbes, we expect to release provider containing this fix next month

**Pull request merged**
