### PR TITLE
Manager info data source

### PR DESCRIPTION
**Pull request by ksamoray**
A container for various information about the NSX manager.
For now, retrieves the software version of the manager.

### CODE REVIEW

**Comment by ksamoray** [comment]
@annakhm maybe it's better to consolidate into `nsxt_management_cluster`?

**Comment by annakhm** [comment]
I don't think we should consolidate it with `nsxt_management_cluster`. But I'm thinking there might be other NSX parameters worth exposing, in which case we should consider generic name for the data source (`nsxt_manager_info`? `nsxt_about`? )

**Review by annakhm — APPROVED** [review]

**Pull request merged**
